# Generated by Django 5.2.4 on 2025-07-29 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, default='0', max_length=255)),
                ('height', models.CharField(blank=True, default='0', max_length=255)),
                ('age', models.CharField(blank=True, default='0', max_length=255)),
                ('gender', models.CharField(blank=True, default='-', max_length=255)),
                ('package', models.CharField(blank=True, default='No package available', max_length=255)),
                ('days_left', models.CharField(blank=True, default='0', max_length=255)),
                ('profile', models.CharField(blank=True, default='user-11.jpg', max_length=255)),
                ('otp_code', models.CharField(default='0', max_length=255)),
                ('reset_code', models.CharField(default='0', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=255, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
