# Generated by Django 5.2.4 on 2025-07-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='recipe_count',
            field=models.IntegerField(default=0),
        ),
    ]
