# Generated by Django 5.2.4 on 2025-07-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_mealplan_recipe_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookcategory',
            name='assigned_audio',
            field=models.IntegerField(default=0),
        ),
    ]
