# Generated by Django 5.2.4 on 2025-07-30 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_audiobookcategory_assigned_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admins.audiobookcategory'),
        ),
    ]
