# Generated by Django 5.2.4 on 2025-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_audiobook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
