# Generated by Django 5.2.4 on 2025-07-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_ecommercepc_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecommercepc',
            old_name='method_id',
            new_name='method',
        ),
    ]
