# Generated by Django 5.2.4 on 2025-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_rename_method_id_ecommercepc_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercepc',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
