# Generated by Django 5.2.4 on 2025-07-31 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_ecommercepc_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagepc',
            old_name='method_id',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='packagepc',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='packagepc',
            name='user_id',
        ),
        migrations.AddField(
            model_name='packagepc',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admins.package'),
        ),
        migrations.AddField(
            model_name='packagepc',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
