# Generated by Django 5.2.4 on 2025-08-05 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_appointment_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.CharField(blank=True, default='0.00', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=models.CharField(blank=True, default='default-intro', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_certificated',
            field=models.CharField(blank=True, default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='video_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='overview',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(blank=True, default='0.00', max_length=255),
        ),
        migrations.AlterField(
            model_name='mealplanrecipe',
            name='video_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='total_price',
            field=models.CharField(blank=True, default='0.00', max_length=255),
        ),
    ]
