# Generated by Django 5.2.4 on 2025-08-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_alter_itemreview_active_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='admins.item'),
        ),
    ]
