# Generated by Django 5.2.4 on 2025-08-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
