# Generated by Django 5.2.4 on 2025-08-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_delete_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
